// <auto-generated />
using System;
using Be3.Pacientes.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Be3.Pacientes.Infrastructure.Migrations
{
    [DbContext(typeof(PacientesDbContext))]
    [Migration("20251122013102_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be3.Pacientes.Domain.Entities.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Convenios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2025, 11, 22, 1, 31, 2, 666, DateTimeKind.Utc).AddTicks(3304),
                            Nome = "Amil",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2025, 11, 22, 1, 31, 2, 666, DateTimeKind.Utc).AddTicks(3306),
                            Nome = "Unimed",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2025, 11, 22, 1, 31, 2, 666, DateTimeKind.Utc).AddTicks(3306),
                            Nome = "Bradesco Saúde",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2025, 11, 22, 1, 31, 2, 666, DateTimeKind.Utc).AddTicks(3307),
                            Nome = "SulAmérica",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CriadoEm = new DateTime(2025, 11, 22, 1, 31, 2, 666, DateTimeKind.Utc).AddTicks(3308),
                            Nome = "NotreDame Intermédica",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Be3.Pacientes.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConvenioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCarteirinha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneFixo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UfRg")
                        .HasColumnType("int");

                    b.Property<string>("ValidadeCarteirinha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.HasIndex("ConvenioId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Be3.Pacientes.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Be3.Pacientes.Domain.Entities.Convenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("ConvenioId");

                    b.Navigation("Convenio");
                });
#pragma warning restore 612, 618
        }
    }
}
